'use strict';

const LANG = {
	'Arabic': 'ar',
	'Bosnian': 'bs',
	'Chinese - Simplified': 'zh',
	'Chinese - Traditional': 'zh-tw',
	'Croatian': 'hr',
	'Dutch': 'nl',
	'English': 'en',
	'French': 'fr',
	'German': 'de',
	'Greek': 'el',
	'Italian': 'it',
	'Polish': 'pl',
	'Portuguese': 'pt',
	'Russian': 'ru',
	'Slovak': 'sk',
	'Spanish': 'es',
	'Swedish': 'sv',
	'Tetum': 'tet',
	'Turkish': 'tr',
	'Ukrainian': 'uk'
};

var domain   = require('domain'),
	config   = require('./config.json'),
	request  = require('request'),
	platform = require('./platform'),
	baseUrl, language;

var _handleException = function (requestId, error) {
	platform.sendResult(requestId, null);
	platform.handleException(error);
};

/**
 * Emitted when device data is received.
 * @param {string} requestId The request id generated by the platform for this service request.
 * @param {object} data The data coming from the device represented as JSON Object.
 */
platform.on('data', function (requestId, data) {
	var req = baseUrl + '/' + data.lat + ',' + data.lng;

	request.get({
		url: req,
		qs: {
			units: 'auto',
			exclude: 'minutely,hourly,daily,alerts,flags',
			lang: language
		}
	}, function (requestError, response, body) {
		if (requestError)
			_handleException(requestId, requestError);
		else if (response.statusCode !== 200)
			_handleException(requestId, new Error(response.statusMessage));
		else {
			var d = domain.create();

			d.once('error', function () {
				_handleException(requestId, new Error('Error parsing response body. Response: ' + body));
				d.exit();
			});

			d.run(function () {
				var responseData = JSON.parse(body);

				var weatherData = responseData.currently;

				platform.sendResult(requestId, JSON.stringify({
					weather_conditions: weatherData
				}));

				platform.log(JSON.stringify({
					title: 'Forecast.io Service Result',
					input: {
						lat: data.lat,
						lng: data.lng
					},
					result: weatherData
				}));

				d.exit();
			});
		}
	});
});

/*
 * Event to listen to in order to gracefully release all resources bound to this service.
 */
platform.on('close', function () {
	platform.notifyClose();
});

/*
 * Listen for the ready event.
 */
platform.once('ready', function (options) {
	baseUrl = 'https://api.forecast.io/forecast/' + options.apikey;
	language = LANG[options.language] || config.language.default;

	platform.log('Forecast.io Service Initialized.');
	platform.notifyReady();
});
