apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Dark-Sky Service
  description: Dark-Sky Service Plugin for the Reekoh IoT Platform. Integrates a Reekoh instance to Dark Sky API to get real-time weather conditions
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Service
  price: 0
  tags:
    - service
    - dark-sky

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      apiKey:
        label: API Key
        type: Password
        maxLength: 1000
        required: true
        help: Kindly specify your Dark Sky API Key for authentication.
      language:
        label: Language
        type: String
        maxLength: 1000
        enum:
          - Arabic
          - Bosnian
          - Chinese - Simplified
          - Chinese - Traditional
          - Croatian
          - Dutch
          - English
          - French
          - German
          - Greek
          - Italian
          - Polish
          - Portuguese
          - Russian
          - Slovak
          - Spanish
          - Swedish
          - Tetum
          - Turkish
          - Ukranian
        help: "(Optional) Return results in the desired language. Default: English"
        default: en
